---
AWSTemplateFormatVersion: "2010-09-09"
Description: The demo configures resources for Field Report demo.

# Parameters:

Resources:
  InboundReports:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Topic: !Ref ReportReceived
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .png

  ReportReceived:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt NewReportQueue.Arn
          Protocol: sqs

  ReportReceivedPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: ReportReceivedTopicPolicy
        Version: 2012-10-17
        Statement:
          - Sid: AllowReceivedReportsFromS3
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref ReportReceived
      Topics:
        - !Ref ReportReceived

  NewReportQueue:
    Type: AWS::SQS::Queue

  NewReportQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: ReportReceivedQueuePolicy
        Version: 2012-10-17
        Statement:
          - Sid: AllowNewReportsFromSNS
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt NewReportQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ReportReceived
      Queues:
        - !Ref NewReportQueue

  ArchiveQueue:
    Type: AWS::SQS::Queue

  ArchiveReports:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FieldReportUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: AllowInboundReports
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Put*
                Resource:
                  - !Join
                    - "/"
                    - - !GetAtt InboundReports.Arn
                      - "*"

  FieldReportUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FieldReportUser

  ReviewUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: AllowReviewReports
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource:
                  - !GetAtt ArchiveQueue.Arn
                  - !GetAtt NewReportQueue.Arn
              - Effect: Allow
                Action:
                  - s3:Get*
                Resource:
                  - !Join
                    - "/"
                    - - !GetAtt InboundReports.Arn
                      - "*"

  ReviewUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ReviewUser

  ArchiveUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: AllowReceiveReports
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource:
                  - !GetAtt ArchiveQueue.Arn
              - Effect: Allow
                Action:
                  - s3:Get*
                Resource:
                  - !Join
                    - "/"
                    - - !GetAtt InboundReports.Arn
                      - "*"
        - PolicyName: AllowArchiveReports
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Put*
                Resource:
                  - !Join
                    - "/"
                    - - !GetAtt ArchiveReports.Arn
                      - "*"

  ArchiveUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref ArchiveUser

Outputs:
  InboundReportsBucketName:
    Description: The name of the bucket for inbound reports.
    Value: !Ref InboundReports
  ReportReceivedTopic:
    Description: The SNS Topic ARN for received reports.
    Value: !Ref ReportReceived
  NewReportQueue:
    Description: The SQS Queue URL for processing new reports.
    Value: !Ref NewReportQueue
  ArchiveReportsBucketName:
    Description: The name of the bucket for archive reports.
    Value: !Ref ArchiveReports
  FieldReportAccessKeyId:
    Description: Access Key Id for use in Field Report app.
    Value: !Ref FieldReportUserAccessKey
  FieldReportSecretAccessKey:
    Description: Secret Access Key for use in Field Report app.
    Value: !GetAtt FieldReportUserAccessKey.SecretAccessKey
  ReviewAccessKeyId:
    Description: Access Key Id for use in Review app.
    Value: !Ref ReviewUserAccessKey
  ReviewSecretAccessKey:
    Description: Secret Access Key for use in Review app.
    Value: !GetAtt ReviewUserAccessKey.SecretAccessKey
  ArchiveQueue:
    Description: The SQS Queue URL for archiving reports.
    Value: !Ref ArchiveQueue
  ArchiveAccessKeyId:
    Description: Access Key Id for use in Archive app.
    Value: !Ref ArchiveUserAccessKey
  ArchiveSecretAccessKey:
    Description: Secret Access Key for use in Archive app.
    Value: !GetAtt ArchiveUserAccessKey.SecretAccessKey
